modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="snom"
version="0.0.1"
displayName="Soulnomicon"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="logo.png"
credits=""
authors="PierKnight100"
description='''
Welcome and thanks for using the Soulnomicon mod! This mod adds new abilities (or spells) which use your soul as fuel! to do this you need, you guessed it, the soulnomicon! A special book found in an ancient dungeon (which is not implemented yet)
'''
[[dependencies.snom]]
    modId="forge"
     mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.snom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
